In [1]:
import pandas as pd

In [3]:
file = "data/raw/yellow_tripdata_2023-01.parquet"

In [5]:
df = pd.read_parquet(file)

FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/yellow_tripdata_2023-01.parquet'

In [13]:
df.head(10)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee,duration
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00,8.433333
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00,6.316667
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00,12.750000
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25,9.616667
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00,10.833333
5,2,2023-01-01 00:50:34,2023-01-01 01:02:52,1.0,1.84,1.0,N,161,137,1,12.8,1.00,0.5,10.00,0.0,1.0,27.80,2.5,0.00,12.300000
6,2,2023-01-01 00:09:22,2023-01-01 00:19:49,1.0,1.66,1.0,N,239,143,1,12.1,1.00,0.5,3.42,0.0,1.0,20.52,2.5,0.00,10.450000
7,2,2023-01-01 00:27:12,2023-01-01 00:49:56,1.0,11.70,1.0,N,142,200,1,45.7,1.00,0.5,10.74,3.0,1.0,64.44,2.5,0.00,22.733333
8,2,2023-01-01 00:21:44,2023-01-01 00:36:40,1.0,2.95,1.0,N,164,236,1,17.7,1.00,0.5,5.68,0.0,1.0,28.38,2.5,0.00,14.933333
9,2,2023-01-01 00:39:42,2023-01-01 00:50:36,1.0,3.01,1.0,N,141,107,2,14.9,1.00,0.5,0.00,0.0,1.0,19.90,2.5,0.00,10.900000

In [6]:
print("Number of columns:", df.shape[1])

Number of columns: 19

In [7]:
# Compute duration in minutes
df["duration"] = (
    df["tpep_dropoff_datetime"] - df["tpep_pickup_datetime"]
).dt.total_seconds() / 60

In [8]:
# Get the standard deviation
std_duration = df["duration"].std()
print("Std of trip durations (min):", round(std_duration, 2))

Std of trip durations (min): 42.59

In [9]:
# Filter to [1, 60] minutes
orig_count = len(df)
df_filtered = df[(df.duration >= 1) & (df.duration <= 60)]
filtered_count = len(df_filtered)

In [12]:
fraction = filtered_count / orig_count
print("As percentage:", round(fraction * 100, 2), "%")

As percentage: 98.12 %

In [14]:
# Cast IDs to strings so DictVectorizer treats them as categories
df["PULocationID"] = df["PULocationID"].astype(str)
df["DOLocationID"] = df["DOLocationID"].astype(str)

In [15]:
# Turn into list of dicts
records = df[["PULocationID", "DOLocationID"]].to_dict(orient="records")

In [17]:
# Fit the vectorizer
from sklearn.feature_extraction import DictVectorizer
dv = DictVectorizer(sparse=False)
X = dv.fit_transform(records)

In [2]:
# Check dimensionality
print("Feature matrix shape:", X.shape)   
print("Number of one-hot columns:", X.shape[1])

NameError: name 'X' is not defined

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model = LinearRegression()    
model.fit(X, df["duration"])

In [ ]:
y_pred = model.predict(X)

rmse = mean_squared_error(y, y_pred, squared=False)
print("Train RMSE:", round(rmse, 2))